Fix UnicodeDecodeError: Make utf-8 encoding explicit
Instead of relying on the system's default and hoping for UTF-8,
explicity set the encoding of known files.

The result is:

Instead of
```
$ LANG=ASCII python ops.py
Traceback (most recent call last):
  File "ops.py", line 6, in <module>
    "siteconfig.json")))
  File "/home/egon/.pyenv/versions/3.6.8/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/egon/.pyenv/versions/3.6.8/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1301: ordinal not in range(128)

$ LANG=C.UTF-8 python ops.py
```
we now get
```
$ LANG=C.UTF-8 python ops.py

$ LANG=ASCII python ops.py
```

Fix #140